"""post_baseline_schema

Revision ID: 7c5b26130061
Revises: 0001_baseline
Create Date: 2026-08-09 20:43:07.317132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c5b26130061'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_soporte',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('prefijo', sa.String(length=10), nullable=True),
    sa.Column('consecutivo_dian', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('nit_proveedor', sa.String(length=20), nullable=True),
    sa.Column('razon_social_proveedor', sa.String(length=250), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('iva', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('cuds', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('estado_dian', sa.String(length=40), nullable=True),
    sa.Column('mensaje_dian', sa.String(length=500), nullable=True),
    sa.Column('ruta_xml', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['terceros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuds'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('documento_soporte_detalles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('impuesto_id', sa.Integer(), nullable=True),
    sa.Column('total_linea', sa.Float(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_soporte.id'], ),
    sa.ForeignKeyConstraint(['impuesto_id'], ['impuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_debito_venta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('prefijo', sa.String(length=10), nullable=True),
    sa.Column('consecutivo_dian', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=250), nullable=True),
    sa.Column('factura_cufe', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('iva', sa.Float(), nullable=False),
    sa.Column('retefuente_id', sa.Integer(), nullable=True),
    sa.Column('reteica_id', sa.Integer(), nullable=True),
    sa.Column('reteiva_id', sa.Integer(), nullable=True),
    sa.Column('valor_retefuente', sa.Float(), nullable=False),
    sa.Column('valor_reteica', sa.Float(), nullable=False),
    sa.Column('valor_reteiva', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('cufe', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('estado_dian', sa.String(length=40), nullable=True),
    sa.Column('mensaje_dian', sa.String(length=500), nullable=True),
    sa.Column('ruta_xml', sa.String(length=500), nullable=True),
    sa.Column('ruta_zip', sa.String(length=500), nullable=True),
    sa.Column('contabilizado', sa.Boolean(), nullable=False),
    sa.Column('asiento_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asiento_id'], ['asientos_contables.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['terceros.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas_venta.id'], ),
    sa.ForeignKeyConstraint(['retefuente_id'], ['impuestos.id'], ),
    sa.ForeignKeyConstraint(['reteica_id'], ['impuestos.id'], ),
    sa.ForeignKeyConstraint(['reteiva_id'], ['impuestos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cufe'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('nota_debito_venta_detalles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nota_debito_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('producto_variante_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('impuesto_id', sa.Integer(), nullable=True),
    sa.Column('precio_incluye_iva', sa.Boolean(), nullable=False),
    sa.Column('total_linea', sa.Float(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['impuesto_id'], ['impuestos.id'], ),
    sa.ForeignKeyConstraint(['nota_debito_id'], ['notas_debito_venta.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['producto_variante_id'], ['producto_variantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_auditoria_fecha'), table_name='auditoria_eventos')
    op.drop_index(op.f('idx_auditoria_usuario'), table_name='auditoria_eventos')
    op.create_foreign_key(None, 'cotizacion_detalles', 'impuestos', ['reteica_id'], ['id'])
    op.create_foreign_key(None, 'cotizacion_detalles', 'producto_variantes', ['producto_variante_id'], ['id'])
    op.create_foreign_key(None, 'cotizacion_detalles', 'impuestos', ['retefuente_id'], ['id'])
    op.create_foreign_key(None, 'cotizacion_detalles', 'impuestos', ['impuesto_id'], ['id'])
    op.create_foreign_key(None, 'cotizaciones', 'impuestos', ['retefuente_id'], ['id'])
    op.create_foreign_key(None, 'cotizaciones', 'impuestos', ['reteiva_id'], ['id'])
    op.create_foreign_key(None, 'cotizaciones', 'impuestos', ['reteica_id'], ['id'])
    op.alter_column('empresa', 'fecha_actualizacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('facturas_compra', sa.Column('retefuente_id', sa.Integer(), nullable=True))
    op.add_column('facturas_compra', sa.Column('reteica_id', sa.Integer(), nullable=True))
    op.add_column('facturas_compra', sa.Column('reteiva_id', sa.Integer(), nullable=True))
    op.add_column('facturas_compra', sa.Column('valor_retefuente', sa.Float(), nullable=False))
    op.add_column('facturas_compra', sa.Column('valor_reteica', sa.Float(), nullable=False))
    op.add_column('facturas_compra', sa.Column('valor_reteiva', sa.Float(), nullable=False))
    op.add_column('facturas_compra', sa.Column('evento_radian_codigo', sa.String(length=10), nullable=True))
    op.add_column('facturas_compra', sa.Column('evento_radian_cude', sa.String(length=100), nullable=True))
    op.add_column('facturas_compra', sa.Column('evento_radian_mensaje', sa.String(length=500), nullable=True))
    op.add_column('facturas_compra', sa.Column('evento_radian_fecha', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'facturas_compra', 'impuestos', ['reteica_id'], ['id'])
    op.create_foreign_key(None, 'facturas_compra', 'impuestos', ['retefuente_id'], ['id'])
    op.create_foreign_key(None, 'facturas_compra', 'impuestos', ['reteiva_id'], ['id'])
    op.drop_constraint(op.f('nota_credito_venta_detalles_nota_credito_id_fkey'), 'nota_credito_venta_detalles', type_='foreignkey')
    op.create_foreign_key(None, 'nota_credito_venta_detalles', 'notas_credito_venta', ['nota_credito_id'], ['id'])
    op.drop_constraint(op.f('orden_compra_detalles_orden_id_fkey'), 'orden_compra_detalles', type_='foreignkey')
    op.create_foreign_key(None, 'orden_compra_detalles', 'ordenes_compra', ['orden_id'], ['id'])
    op.create_foreign_key(None, 'producto_precios', 'impuestos', ['impuesto_id'], ['id'])
    op.alter_column('producto_variantes', 'atributos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('productos', 'atributos_variante',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_unique_constraint(None, 'productos', ['codigo_barras'])
    op.create_foreign_key(None, 'productos', 'impuestos', ['impuesto_venta_id'], ['id'])
    op.create_foreign_key(None, 'productos', 'impuestos', ['impuesto_compra_id'], ['id'])
    op.drop_constraint(op.f('recepcion_compra_detalles_recepcion_id_fkey'), 'recepcion_compra_detalles', type_='foreignkey')
    op.create_foreign_key(None, 'recepcion_compra_detalles', 'recepciones_compra', ['recepcion_id'], ['id'])
    op.alter_column('roles', 'modulos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('terceros', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('terceros', 'fecha_actualizacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('terceros_numero_documento_key'), 'terceros', type_='unique')
    op.create_index(op.f('ix_terceros_numero_documento'), 'terceros', ['numero_documento'], unique=True)
    op.create_foreign_key(None, 'terceros', 'impuestos', ['reteiva_id'], ['id'])
    op.create_foreign_key(None, 'terceros', 'impuestos', ['retefuente_id'], ['id'])
    op.create_foreign_key(None, 'terceros', 'listas_precio', ['lista_precio_id'], ['id'])
    op.create_foreign_key(None, 'terceros', 'impuestos', ['reteica_id'], ['id'])
    op.create_foreign_key(None, 'usuarios', 'roles', ['rol_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_constraint(None, 'terceros', type_='foreignkey')
    op.drop_constraint(None, 'terceros', type_='foreignkey')
    op.drop_constraint(None, 'terceros', type_='foreignkey')
    op.drop_constraint(None, 'terceros', type_='foreignkey')
    op.drop_index(op.f('ix_terceros_numero_documento'), table_name='terceros')
    op.create_unique_constraint(op.f('terceros_numero_documento_key'), 'terceros', ['numero_documento'], postgresql_nulls_not_distinct=False)
    op.alter_column('terceros', 'fecha_actualizacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('terceros', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('roles', 'modulos',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint(None, 'recepcion_compra_detalles', type_='foreignkey')
    op.create_foreign_key(op.f('recepcion_compra_detalles_recepcion_id_fkey'), 'recepcion_compra_detalles', 'recepciones_compra', ['recepcion_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_constraint(None, 'productos', type_='unique')
    op.alter_column('productos', 'atributos_variante',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('producto_variantes', 'atributos',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'producto_precios', type_='foreignkey')
    op.drop_constraint(None, 'orden_compra_detalles', type_='foreignkey')
    op.create_foreign_key(op.f('orden_compra_detalles_orden_id_fkey'), 'orden_compra_detalles', 'ordenes_compra', ['orden_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'nota_credito_venta_detalles', type_='foreignkey')
    op.create_foreign_key(op.f('nota_credito_venta_detalles_nota_credito_id_fkey'), 'nota_credito_venta_detalles', 'notas_credito_venta', ['nota_credito_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'facturas_compra', type_='foreignkey')
    op.drop_constraint(None, 'facturas_compra', type_='foreignkey')
    op.drop_constraint(None, 'facturas_compra', type_='foreignkey')
    op.drop_column('facturas_compra', 'evento_radian_fecha')
    op.drop_column('facturas_compra', 'evento_radian_mensaje')
    op.drop_column('facturas_compra', 'evento_radian_cude')
    op.drop_column('facturas_compra', 'evento_radian_codigo')
    op.drop_column('facturas_compra', 'valor_reteiva')
    op.drop_column('facturas_compra', 'valor_reteica')
    op.drop_column('facturas_compra', 'valor_retefuente')
    op.drop_column('facturas_compra', 'reteiva_id')
    op.drop_column('facturas_compra', 'reteica_id')
    op.drop_column('facturas_compra', 'retefuente_id')
    op.alter_column('empresa', 'fecha_actualizacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'cotizaciones', type_='foreignkey')
    op.drop_constraint(None, 'cotizaciones', type_='foreignkey')
    op.drop_constraint(None, 'cotizaciones', type_='foreignkey')
    op.drop_constraint(None, 'cotizacion_detalles', type_='foreignkey')
    op.drop_constraint(None, 'cotizacion_detalles', type_='foreignkey')
    op.drop_constraint(None, 'cotizacion_detalles', type_='foreignkey')
    op.drop_constraint(None, 'cotizacion_detalles', type_='foreignkey')
    op.create_index(op.f('idx_auditoria_usuario'), 'auditoria_eventos', ['usuario'], unique=False)
    op.create_index(op.f('idx_auditoria_fecha'), 'auditoria_eventos', [sa.literal_column('fecha DESC')], unique=False)
    op.drop_table('nota_debito_venta_detalles')
    op.drop_table('notas_debito_venta')
    op.drop_table('documento_soporte_detalles')
    op.drop_table('documentos_soporte')
    # ### end Alembic commands ###
