"""Tokens de color del design system NEXUS."""

PRIMARY = "#1B4F8A"
PRIMARY_HOVER = "#2563A8"
PRIMARY_PRESSED = "#0F3A66"

SUCCESS = "#065F46"
WARNING = "#B45309"
DANGER = "#B91C1C"
INFO = "#1D4ED8"

BACKGROUND = "#E8F0F8"
SURFACE = "#FFFFFF"
SURFACE_ALT = "#F5F7FB"

TEXT = "#1A3A5C"
TEXT_SECONDARY = "#6B7280"
TEXT_DISABLED = "#9CA3AF"

BORDER = "#B0C4D8"
BORDER_FOCUS = "#1B4F8A"
BORDER_FORM_GROUP = "#D8DEE9"


class Colores:
    """
    Compatibilidad con ``Estilos`` y código legado.
    """

    PRIMARIO = PRIMARY
    PRIMARIO_HOVER = PRIMARY_HOVER
    PRIMARIO_PRESSED = PRIMARY_PRESSED

    EXITO = SUCCESS
    ADVERTENCIA = WARNING
    PELIGRO = DANGER
    INFORMACION = INFO

    FONDO = BACKGROUND
    SUPERFICIE = SURFACE
    SUPERFICIE_ALT = SURFACE_ALT

    TEXTO = TEXT
    TEXTO_SECUNDARIO = TEXT_SECONDARY
    TEXTO_DESHABILITADO = TEXT_DISABLED

    BORDE = BORDER
    BORDE_FOCO = BORDER_FOCUS
    BORDE_GRUPO_FORM = BORDER_FORM_GROUP
