"""Tokens de espaciado y tamaño del design system NEXUS."""

ESPACIADO_4 = 4
ESPACIADO_8 = 8
ESPACIADO_12 = 12
ESPACIADO_16 = 16
ESPACIADO_24 = 24
ESPACIADO_32 = 32

RADIO_PEQUEÑO = 4
RADIO_MEDIO = 6
RADIO_GRANDE = 8

CONTROL_SM = 28
CONTROL_MD = 36
CONTROL_LG = 44

FORM_MARGEN = 20
FORM_ESPACIO_HORIZONTAL = 24
FORM_ESPACIO_VERTICAL = 14
FORM_GRUPO_MARGEN = 16
FORM_GRUPO_ESPACIO_H = 26
FORM_GRUPO_ESPACIO_V = 10
